### ISSUE TITLE
请教，该项目里的 list 是线程安全的吗？

### ISSUE THREAD

**Issue by NikolaDi** [dukelec/cdbus_bridge#1]
我想在linux 多线程环境中使用，是不是还要自己添加互斥锁？

**Comment by NikolaDi** [comment]
是不是只要在 list_head_t 里加一个 pthread_mutex_t 就行了吧

**Comment by dukelec** [comment]
我的這個版本不是線程安全的。
可以你那樣改，也可以考慮把鎖加在上一層的結構體中。
另外，linux kernel 中的 list 大多都是免鎖，你也可以瞭解一下。

**Comment by NikolaDi** [comment]
thanks
